name: Deploy manual para Firebase Hosting

on:
  workflow_dispatch:  # <- Isso habilita o botão "Run workflow" no GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy para Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
        env:
          FIREBASE_PROJECT: calculator-mc-647a9
